import { createTag } from "../core/tag.ts";
import type { Func } from "../core/type.ts";

// // export const Div = createTag("div");
//// export const Span = createTag("span");
export const p: Func<HTMLParagraphElement> = createTag("p");
export const paragraph: Func<HTMLParagraphElement> = createTag("p");

export const ul: Func<HTMLUListElement> = createTag("ul");
export const li: Func<HTMLElement> = createTag("li");
export const ol: Func<HTMLOListElement> = createTag("ol");

//// export const Button = createTag("button");
//// export const Btn = createTag("button");
// // export const Select = createTag("select");
// // export const Option = createTag("option");
// //export const Input = createTag("input");
// // export const TextArea = createTag("textarea");
// // export const Label = createTag("label");

// //export const IMG = createTag("img");
// export const Image = createTag("img");
export const iframe: Func<HTMLIFrameElement> = createTag("iframe");
export const embed: Func<HTMLIFrameElement> = createTag("iframe");
export const canvas: Func<HTMLCanvasElement> = createTag("canvas");
// export const Svg = createTag("svg");

export const br: Func<HTMLBRElement> = createTag("br");
export const hr: Func<HTMLHRElement> = createTag("hr");
export const strong: Func<HTMLElement> = createTag("strong");
export const em: Func<HTMLElement> = createTag("em");
export const small: Func<HTMLElement> = createTag("small");
export const b: Func<HTMLElement> = createTag("b");
export const i: Func<HTMLElement> = createTag("i");
export const u: Func<HTMLElement> = createTag("u");

export const blockQuote: Func<HTMLElement> = createTag("blockquote");
export const code: Func<HTMLElement> = createTag("code");
export const pre: Func<HTMLPreElement> = createTag("pre");
export const kbd: Func<HTMLElement> = createTag("kbd");
export const q: Func<HTMLQuoteElement> = createTag("q");
export const samp: Func<HTMLElement> = createTag("samp");
export const time: Func<HTMLTimeElement> = createTag("time");
export const address: Func<HTMLElement> = createTag("address");
export const s: Func<HTMLElement> = createTag("s");
export const del: Func<HTMLElement> = createTag("del");
export const ins: Func<HTMLElement> = createTag("ins");
export const sub: Func<HTMLElement> = createTag("sub");
export const sup: Func<HTMLElement> = createTag("sup");
//// export const Mark= createTag("mark");
//// export const FOOTER = createTag("footer");
//// export const HEADER = createTag("header");
// //export const MAIN = createTag("main");
//// export const NAV = createTag("nav");
//// export const SECTION = createTag("section");
//// export const ARTICLE = createTag("article");
// //export const ASIDE = createTag("aside");
export const timeTag: Func<HTMLTimeElement> = createTag("time");
export const details: Func<HTMLDetailsElement> = createTag("details");
export const summary: Func<HTMLElement> = createTag("summary");
export const dialog = createTag("dialog");
export const caption: Func<HTMLTableCaptionElement> = createTag("caption");
export const table: Func<HTMLTableElement> = createTag("table");
export const thead: Func<HTMLTableCellElement> = createTag("thead");
export const tbody: Func<HTMLTableCellElement> = createTag("tbody");
export const tfoot: Func<HTMLTableCellElement> = createTag("tfoot");
export const tr: Func<HTMLTableCellElement> = createTag("tr");
export const th: Func<HTMLTableCellElement> = createTag("th");
export const td: Func<HTMLTableCellElement> = createTag("td");
export const abbr: Func<HTMLElement> = createTag("abbr");
